# Profile: Production (Docker & Kubernetes)
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://discovery-service:8761/eureka/}

jwt.secret=${JWT_SECRET}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.security=INFO
